### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by katgirl**
Supports Contao 5, unsupported dependencies removed

### CODE REVIEW

**Comment by denniserdmann** [comment]
Grid Extension does nor work with Contao 5 at the moment. We will release a new version in the following weeks

**Comment by katgirl** [comment]
Yes it does, I just have a page online that already uses it. 

Here the composer.json

```
{
    "type": "project",
    "require": {
        "contao/conflicts": "*@dev",
        "contao/manager-bundle": "5.0.*",
        "contao/news-bundle": "5.0.*",
        "contao/newsletter-bundle": "5.0.*",
        "erdmannfreunde/contao-grid-bundle": "*@dev",
        "erdmannfreunde/euf_nutshell": "*@dev",
        "madeyourday/contao-rocksolid-custom-elements": "^2.4"
    },
    "extra": {
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "@php vendor/bin/contao-setup"
        ],
        "post-update-cmd": [
            "@php vendor/bin/contao-setup"
        ]
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/katgirl/contao-grid-bundle.git"
        },
        {
            "type": "vcs",
            "url": "https://github.com/katgirl/euf_nutshell.git"
        }
    ]
}
```

**Comment by denniserdmann** [comment]
Try to create a column-start element. There should be an error.

**Comment by katgirl** [comment]
Thanks, I had not needed that yet :-)

**Pull request closed without merging**
